module.exports = [
  {
    id: 1,
    name: 'Bottega Louie',
    description: 'Italian',
    photos: null,
    rating: '4',
    price: '$$',
    reviewCount: 18264,
    popularity: null,
    address: '700 S Grand Ave',
    city: 'Los Angeles',
    zip: '90017',
    state: 'CA',
    country: 'US',
    latitude: '34.047056',
    longitude: '-118.256544',
    isVisible: true,
    transactions: [
      'delivery',
    ],
    hours: null,
    phone: '+12138021470',
    tags: null,
    photo: 'https://s3-media1.fl.yelpcdn.com/bphoto/rAImnKvUNcNY8i6qEDWrZA/o.jpg',
    yelpId: 'TkFEKhsCixPWlShULKvMdQ',
    createdAt: '2023-06-14T15:38:36.263Z',
  },
];
